<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.flix29</groupId>
        <artifactId>sprout</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>sprout-processor</artifactId>

    <name>Sprout Processor</name>
    <description>Compile-time REST scaffolding for Spring Boot - Processor</description>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>flix29</id>
            <name>Felix Hallerbach</name>
            <email>info@flix29.de</email>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:https://github.com/Flix-29/Sprout.git</connection>
        <developerConnection>scm:git:git@github.com:flix-29/Sprout.git</developerConnection>
        <url>https://github.com/Flix-29/Sprout</url>
    </scm>
    <url>https://github.com/Flix-29/Sprout</url>
    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/Flix-29/Sprout/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitHub Actions</system>
        <url>https://github.com/Flix-29/Sprout/actions</url>
    </ciManagement>

    <dependencies>
        <dependency>
            <groupId>de.flix29</groupId>
            <artifactId>sprout-annotations</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup</groupId>
            <artifactId>javapoet</artifactId>
            <version>${javapoet.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service-annotations</artifactId>
            <version>${autoservice.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.auto.service</groupId>
                            <artifactId>auto-service</artifactId>
                            <version>${autoservice.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>