package de.flix29.processor;

import com.google.auto.service.AutoService;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;
import de.flix29.annotations.SproutResource;
import java.io.IOException;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

@AutoService(Processor.class)
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class SproutProcessor extends AbstractProcessor {

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return Set.of(SproutResource.class.getCanonicalName());
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element e : roundEnv.getElementsAnnotatedWith(SproutResource.class)) {
            if (!(e instanceof TypeElement type)) {
                continue;
            }
            SproutResource annotation = type.getAnnotation(SproutResource.class);

            String simpleName = type.getSimpleName().toString();
            String derivedPath = "/api/" + simpleName.toLowerCase() + "s";
            String path = (annotation.path() != null && !annotation.path().isBlank()) ? annotation.path() : derivedPath;

            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "[Sprout] Generating marker for " + simpleName + " at path " + path);

            String pkg = "de.flix29.generated";
            String className = simpleName + "SproutMarker";

            FieldSpec pathField = FieldSpec
                    .builder(String.class, "PATH", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", path).build();

            TypeSpec marker = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                    .addJavadoc("Generated by SproutProcessor for {@code $L}.\n", simpleName).addField(pathField)
                    .build();

            JavaFile jf = JavaFile.builder(pkg, marker).skipJavaLangImports(true).build();
            try {
                jf.writeTo(processingEnv.getFiler());
            } catch (IOException ex) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                        "Failed to write marker class for " + simpleName + ": " + ex.getMessage());
            }
        }
        return false;
    }
}
